name: pr-visualizer

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  visualizer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        id: build
        run: |
          npm install
          npm run build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/stats.html